package com.pravera.flutter_activity_recognition.erros

enum class ErrorCodes {
	ACTIVITY_NOT_REGISTERED,
	PERMISSION_REQUEST_CANCELLED,
	ACTIVITY_UPDATES_REQUEST_FAILED,
	ACTIVITY_UPDATES_REMOVE_FAILED,
	ACTIVITY_DATA_ENCODING_FAILED
}
